-- AgriSync AI - PostgreSQL Data Warehouse
-- Grain: one FactSales row per order line

DROP SCHEMA IF EXISTS dw CASCADE;
CREATE SCHEMA dw AUTHORIZATION agrisync_etl;

SET search_path TO dw, public;

CREATE TABLE dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL UNIQUE,
    day INTEGER NOT NULL CHECK (day BETWEEN 1 AND 31),
    month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    quarter INTEGER NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    year INTEGER NOT NULL
);

CREATE TABLE dim_zone (
    zone_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INTEGER NOT NULL UNIQUE,
    zone_name VARCHAR(150) NOT NULL,
    description TEXT
);

CREATE TABLE dim_client (
    client_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL UNIQUE,
    client_name VARCHAR(150) NOT NULL,
    pricing_category VARCHAR(20),
    zone_id INTEGER NOT NULL
);

CREATE TABLE dim_product (
    product_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL UNIQUE,
    product_name VARCHAR(150) NOT NULL,
    category VARCHAR(100),
    reference VARCHAR(100) UNIQUE,
    current_price NUMERIC(12, 2)
        CHECK (current_price >= 0),
    stock_quantity INTEGER
        CHECK (stock_quantity >= 0)
);

CREATE TABLE dim_user (
    user_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    user_name VARCHAR(150) NOT NULL,
    role VARCHAR(50),
    zone_id INTEGER NOT NULL
);

CREATE TABLE fact_sales (
    sales_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key INTEGER NOT NULL,
    client_key INTEGER NOT NULL,
    product_key INTEGER NOT NULL,
    user_key INTEGER NOT NULL,
    zone_key INTEGER NOT NULL,
    order_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL
        CHECK (unit_price >= 0),
    line_total NUMERIC(14, 2) NOT NULL
        CHECK (line_total >= 0),
    order_status VARCHAR(50),

    CONSTRAINT fk_sales_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_sales_client
        FOREIGN KEY (client_key)
        REFERENCES dim_client(client_key),

    CONSTRAINT fk_sales_product
        FOREIGN KEY (product_key)
        REFERENCES dim_product(product_key),

    CONSTRAINT fk_sales_user
        FOREIGN KEY (user_key)
        REFERENCES dim_user(user_key),

    CONSTRAINT fk_sales_zone
        FOREIGN KEY (zone_key)
        REFERENCES dim_zone(zone_key)
);

CREATE INDEX idx_fact_sales_date
    ON fact_sales(date_key);

CREATE INDEX idx_fact_sales_client
    ON fact_sales(client_key);

CREATE INDEX idx_fact_sales_product
    ON fact_sales(product_key);

CREATE INDEX idx_fact_sales_user
    ON fact_sales(user_key);

CREATE INDEX idx_fact_sales_zone
    ON fact_sales(zone_key);

CREATE INDEX idx_fact_sales_order
    ON fact_sales(order_id);