# Generated by Django 4.2.7 on 2026-04-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0002_order_orderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.FloatField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='up_to_date', max_length=50)),
                ('delay_days', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_api.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_api.order')),
            ],
        ),
    ]
